In [1]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in c:\users\harik\appdata\local\programs\python\python39\lib\site-packages (0.12.4)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\harik\appdata\local\programs\python\python39\lib\site-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: numpy>=1.17.3 in c:\users\harik\appdata\local\programs\python\python39\lib\site-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\harik\appdata\local\programs\python\python39\lib\site-packages (from imbalanced-learn) (3.6.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\harik\appdata\local\programs\python\python39\lib\site-packages (from imbalanced-learn) (1.3.2)
Requirement already satisfied: scipy>=1.5.0 in c:\users\harik\appdata\local\programs\python\python39\lib\site-packages (from imbalanced-learn) (1.13.1)

WARNING: Ignoring invalid distribution -andas (c:\users\harik\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -andas (c:\users\harik\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -andas (c:\users\harik\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -andas (c:\users\harik\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -andas (c:\users\harik\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -andas (c:\users\harik\appdata\local\programs\python\python39\lib\site-packages)
WARNING: You are using pip version 22.0.4; however, version 25.3 is available.
You should consider upgrading via the 'C:\Users\harik\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [2]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [3]:
df = pd.read_csv('tel_churn.csv')

In [4]:
df.head(20)

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29.85,29.85,0,True,False,False,True,True,...,False,False,True,False,True,False,False,False,False,False
1,1,0,56.95,1889.50,0,False,True,True,False,True,...,False,False,False,True,False,False,True,False,False,False
2,2,0,53.85,108.15,1,False,True,True,False,True,...,False,False,False,True,True,False,False,False,False,False
3,3,0,42.30,1840.75,0,False,True,True,False,True,...,True,False,False,False,False,False,False,True,False,False
4,4,0,70.70,151.65,1,True,False,True,False,True,...,False,False,True,False,True,False,False,False,False,False
5,5,0,99.65,820.50,1,True,False,True,False,True,...,False,False,True,False,True,False,False,False,False,False
6,6,0,89.10,1949.40,0,False,True,True,False,False,...,False,True,False,False,False,True,False,False,False,False
7,7,0,29.75,301.90,0,True,False,True,False,True,...,False,False,False,True,True,False,False,False,False,False
8,8,0,104.80,3046.05,1,True,False,False,True,True,...,False,False,True,False,False,False,True,False,False,False
9,9,0,56.15,3487.95,0,False,True,True,False,False,...,True,False,False,False,False,False,False,False,False,True
10,10,0,49.95,587.45,0,False,True,False,True,False,...,False,False,False,True,False,True,False,False,False,False
11,11,0,18.95,326.80,0,False,True,True,False,True,...,False,True,False,False,False,True,False,False,False,False
12,12,0,100.35,5681.10,0,False,True,False,True,True,...,False,True,False,False,False,False,False,False,True,False
13,13,0,103.70,5036.30,1,False,True,True,False,True,...,True,False,False,False,False,False,False,False,True,False
14,14,0,105.50,2686.05,0,False,True,True,False,True,...,False,False,True,False,False,False,True,False,False,False
15,15,0,113.25,7895.15,0,True,False,False,True,False,...,False,True,False,False,False,False,False,False,False,True
16,16,0,20.65,1022.95,0,True,False,True,False,True,...,False,False,False,True,False,False,False,False,True,False
17,17,0,106.70,7382.25,0,False,True,True,False,False,...,True,False,False,False,False,False,False,False,False,True
18,18,0,55.20,528.35,1,True,False,False,True,False,...,False,True,False,False,True,False,False,False,False,False
19,19,0,90.05,1862.90,0,True,False,True,False,True,...,False,False,True,False,False,True,False,False,False,False

In [5]:
df = df.drop("Unnamed: 0", axis = 1)

In [6]:
df.head(20)

,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,0,True,False,False,True,True,False,...,False,False,True,False,True,False,False,False,False,False
1,0,56.95,1889.50,0,False,True,True,False,True,False,...,False,False,False,True,False,False,True,False,False,False
2,0,53.85,108.15,1,False,True,True,False,True,False,...,False,False,False,True,True,False,False,False,False,False
3,0,42.30,1840.75,0,False,True,True,False,True,False,...,True,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,1,True,False,True,False,True,False,...,False,False,True,False,True,False,False,False,False,False
5,0,99.65,820.50,1,True,False,True,False,True,False,...,False,False,True,False,True,False,False,False,False,False
6,0,89.10,1949.40,0,False,True,True,False,False,True,...,False,True,False,False,False,True,False,False,False,False
7,0,29.75,301.90,0,True,False,True,False,True,False,...,False,False,False,True,True,False,False,False,False,False
8,0,104.80,3046.05,1,True,False,False,True,True,False,...,False,False,True,False,False,False,True,False,False,False
9,0,56.15,3487.95,0,False,True,True,False,False,True,...,True,False,False,False,False,False,False,False,False,True
10,0,49.95,587.45,0,False,True,False,True,False,True,...,False,False,False,True,False,True,False,False,False,False
11,0,18.95,326.80,0,False,True,True,False,True,False,...,False,True,False,False,False,True,False,False,False,False
12,0,100.35,5681.10,0,False,True,False,True,True,False,...,False,True,False,False,False,False,False,False,True,False
13,0,103.70,5036.30,1,False,True,True,False,True,False,...,True,False,False,False,False,False,False,False,True,False
14,0,105.50,2686.05,0,False,True,True,False,True,False,...,False,False,True,False,False,False,True,False,False,False
15,0,113.25,7895.15,0,True,False,False,True,False,True,...,False,True,False,False,False,False,False,False,False,True
16,0,20.65,1022.95,0,True,False,True,False,True,False,...,False,False,False,True,False,False,False,False,True,False
17,0,106.70,7382.25,0,False,True,True,False,False,True,...,True,False,False,False,False,False,False,False,False,True
18,0,55.20,528.35,1,True,False,False,True,False,True,...,False,True,False,False,True,False,False,False,False,False
19,0,90.05,1862.90,0,True,False,True,False,True,False,...,False,False,True,False,False,True,False,False,False,False

In [7]:
#create x and y variables

x = df.drop('Churn',axis = 1)
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,True,False,False,True,True,False,True,...,False,False,True,False,True,False,False,False,False,False
1,0,56.95,1889.50,False,True,True,False,True,False,False,...,False,False,False,True,False,False,True,False,False,False
2,0,53.85,108.15,False,True,True,False,True,False,False,...,False,False,False,True,True,False,False,False,False,False
3,0,42.30,1840.75,False,True,True,False,True,False,True,...,True,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,True,False,True,False,True,False,False,...,False,False,True,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,84.80,1990.50,False,True,False,True,False,True,False,...,False,False,False,True,False,True,False,False,False,False
7028,0,103.20,7362.90,True,False,False,True,False,True,False,...,False,True,False,False,False,False,False,False,False,True
7029,0,29.60,346.45,True,False,False,True,False,True,True,...,False,False,True,False,True,False,False,False,False,False
7030,1,74.40,306.60,False,True,False,True,True,False,False,...,False,False,False,True,True,False,False,False,False,False
7031,0,105.65,6844.50,False,True,True,False,True,False,False,...,True,False,False,False,False,False,False,False,False,True

In [42]:
#creating X & Y variables

y = df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [43]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)

*`Decition tree classifier`*

In [44]:
model_dt = DecisionTreeClassifier(criterion = 'gini', random_state = 100, max_depth = 6, min_samples_leaf = 8)

In [45]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [46]:
y_predict = model_dt.predict(x_test)

In [47]:
y_predict

array([0, 0, 1, ..., 0, 0, 0], shape=(1407,))

In [48]:
model_dt.score(x_test,y_predict)

1.0

In [49]:
print(classification_report(y_test,y_predict,labels = [0,1]))

              precision    recall  f1-score   support

           0       0.82      0.89      0.85      1024
           1       0.62      0.49      0.55       383

    accuracy                           0.78      1407
   macro avg       0.72      0.69      0.70      1407
weighted avg       0.77      0.78      0.77      1407

In [50]:
pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn) (2.3.4)
Requirement already satisfied: scipy<2,>=1.11.4 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn) (1.7.2)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn) (1.5.2)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from imbalanced-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [51]:
sm = SMOTEENN()
x_resampled, y_resampled = sm.fit_resample(x, y)

In [52]:
xk_train, xk_test, yk_train, yk_test = train_test_split(x_resampled,y_resampled,test_size = 0.2)

In [53]:
model_dt_smote = DecisionTreeClassifier(criterion = 'gini', random_state = 100, max_depth = 6, min_samples_leaf = 8)

In [54]:
model_dt_smote.fit(xk_train, yk_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [55]:
y_predict_smote = model_dt_smote.predict(xk_test)

In [56]:
print(classification_report(yk_test,y_predict_smote, labels = [0,1]))

              precision    recall  f1-score   support

           0       0.92      0.93      0.93       529
           1       0.94      0.94      0.94       653

    accuracy                           0.93      1182
   macro avg       0.93      0.93      0.93      1182
weighted avg       0.93      0.93      0.93      1182

In [57]:
print(confusion_matrix(yk_test,y_predict_smote))

[[492  37]
 [ 40 613]]

*Random Forest classifier*

In [58]:
from sklearn.ensemble import RandomForestClassifier

In [59]:
model_rf = RandomForestClassifier(n_estimators = 100,criterion = 'gini', random_state = 100, max_depth = 6, min_samples_leaf = 8)
model_rf.fit(x_train,y_train)
y_predict_rf = model_rf.predict(x_test)

In [60]:
print(classification_report(y_test,y_predict,labels = [0,1]))

              precision    recall  f1-score   support

           0       0.82      0.89      0.85      1024
           1       0.62      0.49      0.55       383

    accuracy                           0.78      1407
   macro avg       0.72      0.69      0.70      1407
weighted avg       0.77      0.78      0.77      1407

In [61]:
sm = SMOTEENN()
x_resampled, y_resampled = sm.fit_resample(x, y)

In [62]:
xk_train, xk_test, yk_train, yk_test = train_test_split(x_resampled,y_resampled,test_size = 0.2)

In [63]:
model_rf_smote = DecisionTreeClassifier(criterion = 'gini', random_state = 100, max_depth = 6, min_samples_leaf = 8)

In [64]:
model_rf_smote.fit(xk_train, yk_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [65]:
y_predict_smote_rf = model_rf_smote.predict(xk_test)

In [66]:
print(classification_report(yk_test,y_predict_smote_rf, labels = [0,1]))

              precision    recall  f1-score   support

           0       0.93      0.92      0.93       534
           1       0.94      0.95      0.94       652

    accuracy                           0.94      1186
   macro avg       0.94      0.93      0.94      1186
weighted avg       0.94      0.94      0.94      1186

In [67]:
print(confusion_matrix(yk_test,y_predict_smote_rf))

[[493  41]
 [ 35 617]]

In [68]:
import pickle

In [41]:
filename = "model.sav"

In [42]:
pickle.dump(model_rf_smote, open(filename, 'wb'))

In [43]:
load_model = pickle.load(open(filename,'rb'))

In [44]:
load_model.score(xk_test,yk_test)

0.9280270956816258